image: python:3

services:
  - postgres:9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  POSTGRES_USER: user01
  POSTGRES_PASSWORD: user01
  POSTGRES_DB: development
  DB_HOST: postgres

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/

stages:
  - test
  - package
  - deploy

test:
  stage: test
  script:
    - pip install --upgrade pip
    - pip install pytest pytest-flake8 pytest-cov
    - pip install  -r requirements.txt
    - FLASK_APP=run flask db upgrade
    - pytest -v --flake8 --cov=app --cov-report=term-missing
