version: '3'
networks:
  web:
    external:
      name: traefik_web

services:
  app:
    build:
      context: .
      args:
        - HTTPS_PROXY=${HTTPS_PROXY}
    expose:
      - 5000
    volumes:
      - ".:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: run
      FLASK_ENV: development
      DATABASE_URI: 'postgresql://user01:user01@rdb/development'
      HTTPS_PROXY: ${HTTPS_PROXY}
    command: flask run --host 0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$USER.entrypoints=front"
      - "traefik.http.routers.$USER.rule=PathPrefix(`/$USER{regex:$$|/.*}`)"
      - "traefik.http.routers.$USER.middlewares=$USER-stripprefix"
      - "traefik.http.middlewares.$USER-stripprefix.stripprefix.prefixes=/$USER"
    networks:
      - web
  rdb:
    image: postgres:9
    environment:
      POSTGRES_USER: user01
      POSTGRES_PASSWORD: user01
      POSTGRES_DB: development
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - web

volumes:
  database:
    driver: local
